import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Inter } from "next/font/google";
import { Abhaya_Libre } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Sales from "@/components/sales";
import Footer from "@/components/footer";


const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
  weight: ["400", "500", "600", "700", "800"],
});

const abhayaLibre = Abhaya_Libre({
  subsets: ["latin"],
  variable: "--font-abhaya-libre",
  display: "swap",
  weight: ["400", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
        <Sales />
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}